### ISSUE TITLE
composer requirements

### ISSUE THREAD

**Issue by stevevu** [dynamic/silverstripe-classname-update-tasks#5]
Hi,

Can you update the composer requirement for recipe-cms, which is now up to 4.x.  The requirements for this module is recipe-cms ^1.0?

thanks!
Steve

**Comment by korthjp17** [comment]
Hi Steve,
We have been going through updating a lot of our modules for this change. Would you be able to submit a PR for this?

**Comment by muskie9** [comment]
Hi @stevevu, sorry, I missed this ticket. The constraint is updated and there is a new tag for this.

**Comment by stevevu** [comment]
Thanks Nic/Jason!  Great module.  I'm surprised SilverStripe didn't mention this as part of the SS4 upgrade guide .

I forked and updated the module so multiple upgrade YAML files can be specified in the config.  We have a project that contains multiple custom modules (e.g. app/ and newsletter/).

thanks again,
Steve
